name: Infra

on:
  push:
    branches:
      - main
    paths:
      - 'packages/infra/**'
      - '.github/workflows/infra.yml'

jobs:
  infra:
    strategy:
      matrix:
        env: ["dev"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/infra/env/${{ matrix.env }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color