name: Site

on:
  push:
    branches:
      - main
    paths:
      - "packages/site/**"
      - ".github/workflows/site.yml"

jobs:
  deploy:
    strategy:
      matrix:
        bucket: ["mysite.roope.dev"]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ matrix.bucket }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build site
      - name: Build
        run: npm run build --workspace=site

      # Export site
      - name: Export
        run: npm run export --workspace=site

      # Deploy
      - name: Deploy files
        run: aws s3 sync packages/site/out s3://${{ env.S3_BUCKET }}/